## WDI: World Development Indicators (World Bank) {.unnumbered}


### Description

Downloads the requested data by using the World Bank's API, parses the
resulting XML file, and formats it in long country-year format.



### Usage

<pre><code class='language-R'>WDI(
  country = "all",
  indicator = "NY.GDP.PCAP.KD",
  start = 1960,
  end = NULL,
  extra = FALSE,
  cache = NULL,
  latest = NULL,
  language = "en"
)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="country">country</code></td>
<td>
Vector of countries (ISO-2 character codes, e.g. &quot;BR&quot;, &quot;US&quot;,
&quot;CA&quot;) for which the data is needed. Using the string &quot;all&quot; instead of
individual iso codes pulls data for every available country.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="indicator">indicator</code></td>
<td>
Character vector of indicators codes. See the WDIsearch()
function. If you supply a named vector, the indicators will be automatically
renamed: <code>c('women_private_sector' = 'BI.PWK.PRVS.FE.ZS')</code>
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="start">start</code></td>
<td>
Start date, usually a year in integer format. Must be 1960 or
greater.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="end">end</code></td>
<td>
End date, usually a year in integer format. Must be greater than
the <code>start</code> argument. If <code>NULL</code>, the end date is set to 5 years in the future.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="extra">extra</code></td>
<td>
TRUE returns extra variables such as region, iso3c code, and
incomeLevel. See Details.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="cache">cache</code></td>
<td>
NULL (optional) a list created by WDIcache() to be used with the extra=TRUE argument.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="latest">latest</code></td>
<td>
Integer indicating the number of most recent non-NA values to get. Default is NULL. If specified, it overrides the start and end dates.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="language">language</code></td>
<td>
ISO-2 code in lower case indicating in which language the characters should be provided. List of languages available with <code>WDI::languages_supported()</code>. Default is English.
</td></tr>
</table>


### Details

It is possible to only specify the <code>indicator</code> and the <code>country</code> arguments, in which case <code>WDI()</code> will return data from 1960 to the last year available on World Bank's website. It is also possible to get only the most recent non-NA values, with <code>latest</code>.

If <code>extra = TRUE</code>, additional variables are provided:


<ul>
<li>status: observation status, e.g is the observation a forecast?

</li>
<li>iso3c

</li>
<li>region

</li>
<li>capital: name of the capital city

</li>
<li>latitude, longitude

</li>
<li>income: income categories of the World Bank

</li>
<li>lending

</li></ul>



### Value

Data frame with country-year observations. You can extract a
data.frame with indicator names and descriptive labels by inspecting the
<code>label</code> attribute of the resulting data.frame: <code>attr(dat, 'label')</code>



### Author(s)

Vincent Arel-Bundock <a href="mailto:vincent.arel-bundock@umontreal.ca">vincent.arel-bundock@umontreal.ca</a>



### Examples
```{r, warning=FALSE, message=FALSE, eval=FALSE}
library(WDI)



WDI(country="all", indicator=c("AG.AGR.TRAC.NO","TM.TAX.TCOM.BC.ZS"),
    start=1990, end=2000)
WDI(country=c("US","BR"), indicator="NY.GNS.ICTR.GN.ZS", start=1999, end=2000,
    extra=TRUE, cache=NULL)

# Rename indicators on the fly
WDI(country = 'CA', indicator = c('women_private_sector' = 'BI.PWK.PRVS.FE.ZS',
                                  'women_public_sector' = 'BI.PWK.PUBS.FE.ZS'))

# Get the 5 latest non-NA values
WDI(country=c("US","BR"), indicator="NY.GNS.ICTR.GN.ZS", latest = 5)




```
