## Search names and descriptions of available WDI series {.unnumbered}


### Description

Data frame with series code, name, description, and source for the WDI series
which match the given criteria



### Usage

<pre><code class='language-R'>WDIsearch(string = "gdp", field = "name", short = TRUE, cache = NULL)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="string">string</code></td>
<td>
Character string. Search for this string using <code>grep</code> with
<code>ignore.case=TRUE</code>.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="field">field</code></td>
<td>
Character string. Search this field. Admissible fields:
'indicator', 'name', 'description', 'sourceDatabase', 'sourceOrganization'
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="short">short</code></td>
<td>
TRUE: Returns only the indicator's code and name. FALSE: Returns
the indicator's code, name, description, and source.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="cache">cache</code></td>
<td>
Data list generated by the <code>WDIcache</code> function. If omitted,
<code>WDIsearch</code> will search a local list of series.
</td></tr>
</table>


### Value

Data frame with code, name, source, and description of all series which
match the criteria.



### Examples
```{r, warning=FALSE, message=FALSE, eval=FALSE}
library(WDI)

WDIsearch(string='gdp', field='name', cache=NULL)
WDIsearch(string='AG.AGR.TRAC.NO', field='indicator', cache=NULL)



```
