library(RJSONIO)
#' WDI: World Development Indicators (World Bank)
#'
#' Downloads the requested data by using the World Bank's API, parses the resulting XML file, and formats it in long country-year format. 
#' 
#' @param country Vector of countries (ISO-2 character codes, e.g. "BR", "US", "CA") for which the data is needed. Using the string "all" instead of individual iso codes pulls data for every available country.
#' @param indicator Character vector of indicators codes. See the WDIsearch() function.
#' @param start First year of data
#' @param end Last year of data
#' @param extra TRUE returns extra variables such as region, iso3c code, and incomeLevel
#' @return Data frame with country-year observations 
#' @author Vincent Arel-Bundock \email{varel@@umich.edu}
#' @examples
#' WDI(country="all", indicator=c("AG.AGR.TRAC.NO","TM.TAX.TCOM.BC.ZS"), start=1990, end=2000)
#' WDI(country=c("US","BR"), indicator="NY.GNS.ICTR.GN.ZS", start=1999, end=2000, extra=TRUE)
WDI <- function(country = "all", indicator = "NY.GNS.ICTR.GN.ZS", start = 2002, end = 2005, extra = FALSE){
    # Sanitize country-indicator combinations
    indicator = gsub('[^a-zA-Z0-9\\.]', '', indicator)
    country   = gsub('[^a-zA-Z]', '', country) # 
    a         = expand.grid(indicator, country)
    # Download
    dat = lapply(1:nrow(a), function(j) try(wdi.dl(a[j,1], a[j,2], start, end), silent=TRUE))
    # Raise warning if download fails 
    good = unlist(lapply(dat, function(i) class(i)) == 'data.frame')
    if(any(!good)){
        a = paste(paste('(', a[,1], '-', a[,2], ')')[!good], collapse=' ; ')
        warning(paste('Unable to download the following: ', a))
        dat = dat[good] 
    }
    # MERGE
    dat = Reduce(function(x,y) merge(x,y,all=TRUE), dat)
    # EXTRAS
    if(extra==TRUE){
	    dat = merge(dat, extra2010, all.x=TRUE)
    }
    return(dat)
}

wdi.dl = function(indicator, country, start, end){
    daturl  = paste("http://api.worldbank.org/countries/", country, "/indicators/", indicator,
                    "?date=",start,":",end, "&per_page=25000", "&format=json", sep = "")
    dat     = fromJSON(daturl)[[2]]
    dat     = data.frame(do.call('rbind', lapply(dat, function(j) cbind(j$country[[1]], j$country[[2]], j$value, j$date))))
    for(i in 1:4){dat[,i] = as.character(dat[,i])}
    dat[,3] = as.numeric(dat[,3])
    dat[,4] = as.numeric(dat[,4])
    colnames(dat) = c('iso2c', 'country', as.character(indicator), 'year')
    return(dat)
}

#' Update the list of available WDI indicators
#'
#' Download an updated list of available WDI indicators from the World Bank website. Returns a data frame for use in the \code{WDIsearch} function. 
#' 
#' @return Series of indicators, sources and descriptions in data frame format  
#' @author Vincent Arel-Bundock \email{varel@@umich.edu}
#' @note Downloading all series information from the World Bank website can take time.
#' The \code{WDI} package ships with a local data object with information on all the series
#' available on 2012-03-31. You can update this database by retrieving a new list using \code{WDIcache}, and  then
#' feeding the resulting object to \code{WDIsearch} via the \code{cache} argument. 
WDIcache = function(){
    daturl = 'http://api.worldbank.org/indicators?per_page=25000&format=json'
    dat    = fromJSON(daturl)[[2]]
    dat    = data.frame('id'=unlist(lapply(dat, function(i) i$id)), 'name'=unlist(lapply(dat, function(i) i$name)), 
                        'source'=unlist(lapply(dat, function(i) i$sourceOrganization)), 'description'=unlist(lapply(dat, function(i) i$sourceNote)))
    for(i in 1:4){
        dat[,i] = as.character(dat[,i])
    }
    return(dat)
}

#' Search names and descriptions of available WDI series
#'
#' Data frame with series code, name, description, and source for the WDI series which match the given criteria
#' 
#' @param string Character string. Search for this string using \code{grep} with \code{ignore.case=TRUE}.
#' @param field Character string. Search this field. Admissible fields: 'indicator', 'name', 'topic', 'description', 'source'
#' @param short TRUE: Returns only the indicator's code and name. FALSE: Returns the indicator's code, name, topic, description, and source.
#' @param cache Data frame generated by the \code{WDIcache} function. If omitted, \code{WDIsearch} will search a local list of series updated on 2012-03-31.  
#' @return Data frame with code, name, source, and description of all series which match the criteria.  
#' @author Vincent Arel-Bundock \email{varel@@umich.edu}
#' @note Downloading all series information from the World Bank website can take time.
#' The \code{WDI} package ships with a local data object with information on all the series
#' available on 2012-03-31. You can update this database by retrieving a new list using \code{WDIcache}, and  then
#' feeding the resulting object to \code{WDIsearch} via the \code{cache} argument. 
#' @examples
#' WDIsearch(string='gdp', field='name', cache=NULL)
#' WDIsearch(string='AG.AGR.TRAC.NO', field='indicator', cache=NULL)
WDIsearch <- function(string="gdp", field="name", short=TRUE, cache=NULL){
    if(!is.null(cache)){
        series = cache    
    }
    matches = grep(string, series[,field], ignore.case=TRUE)
    if(short){
        out = series[matches, c('id', 'name')]
    }else{
        out = series[matches,]
    }
    return(out)
}

#' World Development Indicators extra country information 
#' 
#' Extra information about countries covered by the WDI. 
#' 
#' @docType data
#' @keywords datasets
#' @name extra2010 
#' @usage extra2010
#' @format data frame
NULL

#' World Development Indicators series 
#' 
#' Code, name, description, source, and topic of all WDI series. Retrieved 2012-03-31
#' 
#' \itemize{
#'   \item indicator code  
#'   \item name name of the series
#'   \item topic topic/category of the variable
#'   \item description detailed description
#'   \item source organization which produced the variable 
#' }
#' 
#' @docType data
#' @keywords datasets
#' @name series 
#' @usage series
#' @format data frame
NULL

